from modules import (
    berry_curvature,
    data_upload,
    esn_prediction,
    fractal_dimension,
    generative_kuramoto,
    graph_sync_analysis,
    hebbian_learning,
    hebbian_learning_viz,
    insight_learning,
    kuramoto_hebbian_sim,
    kuramoto_sim,
    lorenz_sim,
    lyapunov_spectrum,
    memory_landscape,
    mlp_predict_lorenz,
    noise_robustness,
    persistent_homology,
    plasticity_dynamics,
    predict_lorenz,
    questions,
    reflection_modul,
    xor_prediction
)

MODULES = {
    "Berry Curvature": berry_curvature.main,
    "Data Upload": data_upload.main,
    "Esn Prediction": esn_prediction.main,
    "Fractal Dimension": fractal_dimension.main,
    "Generative Kuramoto": generative_kuramoto.main,
    "Graph Sync Analysis": graph_sync_analysis.main,
    "Hebbian Learning": hebbian_learning.main,
    "Hebbian Learning Visualization": hebbian_learning_viz.main,
    "Insight Learning": insight_learning.main,
    "Kuramoto-Hebbian Simulation": kuramoto_hebbian_sim.main,
    "Kuramoto Simulation": kuramoto_sim.main,
    "Lorenz Simulation": lorenz_sim.main,
    "Lyapunov Spectrum": lyapunov_spectrum.main,
    "Memory Landscape": memory_landscape.main,
    "MLP Predict Lorenz": mlp_predict_lorenz.main,
    "Noise Robustness": noise_robustness.main,
    "Persistent Homology": persistent_homology.main,
    "Plasticity Dynamics": plasticity_dynamics.main,
    "Predict Lorenz": predict_lorenz.main,
    "Questions": questions.main,
    "Scientific Reflection": reflection_modul.main,
    "XOR Prediction": xor_prediction.main
}
